---
engines:
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 110
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: false
ratings:
  paths:
  - "src/**.js"
exclude_paths:
- "yarn.lock"
- "gulpfile.js"
- "README.md"
- "**.json"
- "dist/"
- "gulp/"
- "LICENSE"